//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicPlaceholders.Webforms.Sublayouts.Grid {
    
    
    public partial class TwoColumn {
        
        /// <summary>
        /// col1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DynamicPlaceholders.Webforms.Control.PlaceholderControl col1;
        
        /// <summary>
        /// col2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DynamicPlaceholders.Webforms.Control.PlaceholderControl col2;
    }
}
